// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Record struct {
	ID        int64
	Date      sql.NullTime
	State     sql.NullString
	Adults    sql.NullInt64
	Children  sql.NullInt64
	Bicycles  sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
