// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countRecords = `-- name: CountRecords :one
SELECT COUNT(*) as count
FROM records
`

func (q *Queries) CountRecords(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecords)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecordsWithFilters = `-- name: CountRecordsWithFilters :one
SELECT COUNT(*) as count
FROM records
WHERE
    (?1 IS NULL OR date LIKE ?1 || '%') AND
    (?2 IS NULL OR state = ?2) AND
    (?3 IS NULL OR adults >= ?3) AND
    (?4 IS NULL OR children >= ?4) AND
    (?5 IS NULL OR bicycles >= ?5)
`

type CountRecordsWithFiltersParams struct {
	DateFilter  interface{}
	StateFilter interface{}
	MinAdults   interface{}
	MinChildren interface{}
	MinBicycles interface{}
}

func (q *Queries) CountRecordsWithFilters(ctx context.Context, arg CountRecordsWithFiltersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecordsWithFilters,
		arg.DateFilter,
		arg.StateFilter,
		arg.MinAdults,
		arg.MinChildren,
		arg.MinBicycles,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (date, state, adults, children, bicycles)
VALUES (?, ?, ?, ?, ?)
`

type CreateRecordParams struct {
	Date     sql.NullTime
	State    sql.NullString
	Adults   sql.NullInt64
	Children sql.NullInt64
	Bicycles sql.NullInt64
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createRecord,
		arg.Date,
		arg.State,
		arg.Adults,
		arg.Children,
		arg.Bicycles,
	)
	return err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records
WHERE id = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, id)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT id, date, state, adults, children, bicycles, created_at, updated_at
FROM records
WHERE id = ?
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.State,
		&i.Adults,
		&i.Children,
		&i.Bicycles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, date, state, adults, children, bicycles, created_at, updated_at
FROM records
ORDER BY date DESC, id DESC
LIMIT ? OFFSET ?
`

type ListRecordsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.State,
			&i.Adults,
			&i.Children,
			&i.Bicycles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsForChart = `-- name: ListRecordsForChart :many
SELECT id, date, state, adults, children, bicycles
FROM records
WHERE
    (? IS NULL OR date >= ?) AND
    (? IS NULL OR date <= ?) AND
    (? IS NULL OR children >= ?) AND
    (? IS NULL OR bicycles >= ?)
ORDER BY date ASC
`

type ListRecordsForChartParams struct {
	Column1  interface{}
	Date     sql.NullTime
	Column3  interface{}
	Date_2   sql.NullTime
	Column5  interface{}
	Children sql.NullInt64
	Column7  interface{}
	Bicycles sql.NullInt64
}

type ListRecordsForChartRow struct {
	ID       int64
	Date     sql.NullTime
	State    sql.NullString
	Adults   sql.NullInt64
	Children sql.NullInt64
	Bicycles sql.NullInt64
}

func (q *Queries) ListRecordsForChart(ctx context.Context, arg ListRecordsForChartParams) ([]ListRecordsForChartRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsForChart,
		arg.Column1,
		arg.Date,
		arg.Column3,
		arg.Date_2,
		arg.Column5,
		arg.Children,
		arg.Column7,
		arg.Bicycles,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsForChartRow
	for rows.Next() {
		var i ListRecordsForChartRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.State,
			&i.Adults,
			&i.Children,
			&i.Bicycles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsWithFilters = `-- name: ListRecordsWithFilters :many
SELECT id, date, state, adults, children, bicycles, created_at, updated_at
FROM records
WHERE
    (?1 IS NULL OR date LIKE ?1 || '%') AND
    (?2 IS NULL OR state = ?2) AND
    (?3 IS NULL OR adults >= ?3) AND
    (?4 IS NULL OR children >= ?4) AND
    (?5 IS NULL OR bicycles >= ?5)
ORDER BY date DESC, id DESC
LIMIT ?7 OFFSET ?6
`

type ListRecordsWithFiltersParams struct {
	DateFilter  interface{}
	StateFilter interface{}
	MinAdults   interface{}
	MinChildren interface{}
	MinBicycles interface{}
	Offset      int64
	Limit       int64
}

func (q *Queries) ListRecordsWithFilters(ctx context.Context, arg ListRecordsWithFiltersParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecordsWithFilters,
		arg.DateFilter,
		arg.StateFilter,
		arg.MinAdults,
		arg.MinChildren,
		arg.MinBicycles,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.State,
			&i.Adults,
			&i.Children,
			&i.Bicycles,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :exec
UPDATE records
SET date = ?, state = ?, adults = ?, children = ?, bicycles = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRecordParams struct {
	Date     sql.NullTime
	State    sql.NullString
	Adults   sql.NullInt64
	Children sql.NullInt64
	Bicycles sql.NullInt64
	ID       int64
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.ExecContext(ctx, updateRecord,
		arg.Date,
		arg.State,
		arg.Adults,
		arg.Children,
		arg.Bicycles,
		arg.ID,
	)
	return err
}
